### ISSUE TITLE
[website] Welcome page zipcode

### ISSUE THREAD

**Issue by GraysonFreking** [Represented/Represented#17]
Summary: Welcome page zipcode does is not user friendly.

Description: "zipcode" text in entry box should not have to be deleted, and should be placeholder instead. On top of this, the current placeholder shouldn't be 01234, gives no indication of what should be entered. I recommend replacing this placeholder with "zip code"

Severity: Low

**Comment by 95rosh** [comment]
Placeholder is now "zipcode" (can be changed easily) instead of "01234", and the Welcome page no longer loads with a string already in the text box.
