### ISSUE TITLE
[website] About Page is not intuitive

### ISSUE THREAD

**Issue by GraysonFreking** [Represented/Represented#19]
Summary: About page is not intuitive, it does not tell me much about the app.

Description: "About" page does not have a lot of information about what service is being provided. The scroll feature is neat, but takes up a lot of unnecessary space, and on top of this users have no indication that they should scroll down to see "Stay Informed" and "Be Heard". It might be beneficial to merge the information here with the welcome page.

Severity: Medium

**Comment by 95rosh** [comment]
Added more informative details as well as a phrase telling the user that they can scroll down for more info.  Closing this for the time being, though the long-term idea of merging the about and welcome pages will probably be implemented at some point.
