### ISSUE TITLE
[website] My Reps page shows "scroll to load more"

### ISSUE THREAD

**Issue by emcleod17** [Represented/Represented#22]
Although there are only a small number of representatives to display there is text suggesting the user scroll to load more. "Scroll down to load more" should only show if there are more to display, otherwise it can be confusing. Shouldn’t be visible if there are no more to load.

Severity: Low

Suggestions: This is likely not necessary.

**Comment by mfortman11** [comment]
Adding more to my-reps and there vote actions clarifies this
