### ISSUE TITLE
[website] Representative images not present

### ISSUE THREAD

**Issue by GraysonFreking** [Represented/Represented#23]
Summary: In certain cases, the representative images are not present

Description: Enter zipcode 55077 --> Legislator: L000587 --> representative image is non-existent. This is fine given that you are scraping the web for images, but if an image is not found, consider using a placeholder image, or reformat the page to accommodate the missing image.

Severity: Low

**Comment by 95rosh** [comment]
This was a good find and a complex fix.  Now, anytime a representative's image cannot be found in any feed, we instead use a default "No Image Available" image with the same dimensions and alignment.
