### ISSUE TITLE
[website] Some Bill Titles Not Present

### ISSUE THREAD

**Issue by JDKardia** [Represented/Represented#25]
## Summary: 
On some Representative Pages, Bill titles won't appear.

## Description:
 In the sponsored bills section of some representatives bills have no titles.
Examples can be seen at:
- zip 53703, Senator Tammy Baldwin
- zip 48103, Senator Debbie Dingell

## Severity:
High

**Comment by 95rosh** [comment]
Added checks for null and non-null titles as needed for Representative Pages.
