### ISSUE TITLE
[website] "Go to bill" confusing for the user

### ISSUE THREAD

**Issue by GraysonFreking** [Represented/Represented#31]
Summary: "Go to bill" is confusing to navigate.

Description: Although styling was reported in a different issue it is also apparent here. The third line from the bottom of the page (usually just "115") has no indication of what it means. Also, for a relatively new user, they may not know what the name of the bill is, so an indication of that would also be helpful.

Severity: Medium

**Comment by 95rosh** [comment]
Added text that displays "Congress: " before "115" (this is the number that signifies which Congress the bill is active in; will almost always be the current Congress number).  Also added the short title (this is the "name of the bill") to the bill page itself.
